language: julia
julia:
- 0.5
- nightly
script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- julia --check-bounds=yes -e 'Pkg.update(); Pkg.clone(pwd()); Pkg.build("InteractiveFixedEffectModels"); Pkg.test("InteractiveFixedEffectModels"; coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("InteractiveFixedEffectModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
notifications:
  email: false
  on_success: never 
  on_failure: change