language: julia
julia:
- 1.0
- 1.1
- 1.2
- nightly
script:
-  if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- julia --project -e 'using Pkg; Pkg.add(PackageSpec(name ="FixedEffects", rev="master")) ; Pkg.add(PackageSpec(name ="FixedEffectModels", rev="master"))  ; Pkg.build(); Pkg.test(; coverage=true)';
matrix:
  allow_failures:
    - julia: nightly
after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
notifications:
  email:
    on_success: never 
    on_failure: change